disabled = false
languageCode = "zh-tw"
hasCJKLanguage = true
languageName = "中文"
weight = 1
title = "１１０號道路"

[params]
  displayName = "中"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006年01月02日"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "拍拍"
#   headline = "I'm only human"
#   bio = "A little bit about you"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"
